[env:m5stack-atom]
platform = espressif32
board = m5stack-atom
framework = arduino
monitor_speed = 115200
upload_speed = 1500000

board_build.filesystem = littlefs

build_flags =
    -D CORE_DEBUG_LEVEL=1

lib_deps =
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    https://github.com/me-no-dev/AsyncTCP.git
    bblanchon/ArduinoJson @ ^6.21.0
    fastled/FastLED @ ^3.9.0